# Generated by Django 5.2 on 2025-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Імя')),
                ('surname', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('second_name', models.CharField(max_length=20, verbose_name='По Батькові')),
                ('phone_number', models.CharField(max_length=13, unique=True, verbose_name='Номер телефону')),
                ('room_id', models.IntegerField(blank=True, null=True, verbose_name='Номер кімнати')),
            ],
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
