# Generated by Django 5.2 on 2025-04-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_delete_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='room_id',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10, unique=True, verbose_name='Номер кімнати')),
                ('room_class', models.CharField(choices=[('standart', 'Стандарт'), ('premium', 'Преміум')], max_length=50, verbose_name='Клас кімнати')),
                ('capacity', models.IntegerField(verbose_name='Місткість кімнати')),
                ('cost', models.IntegerField(verbose_name='Ціна')),
                ('status', models.IntegerField(choices=[('available', 'Доступна'), ('unavailable', 'Зайнята')], default='доступна', max_length=20, verbose_name='Статус кімнати')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client', verbose_name='Клієнт')),
            ],
        ),
    ]
