# Generated by Django 5.2 on 2025-04-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_client_room_id_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('unavailable', 'Зайнята')], default='доступна', max_length=20, verbose_name='Статус кімнати'),
        ),
    ]
