# Generated by Django 5.2 on 2025-04-14 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва послуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Дата заселення')),
                ('check_out_date', models.DateField(verbose_name='Дата виселення')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна ціна')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронювання')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клієнт')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Номер кімнати')),
                ('additional_services', models.ManyToManyField(blank=True, to='main.service', verbose_name='Додаткові послуги')),
            ],
        ),
    ]
