# Generated by Django 5.2 on 2025-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість днів'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Загальна ціна'),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='По Батькові'),
        ),
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за ніч'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Доступна'), ('unavailable', 'Зайнята')], default='available', max_length=20, verbose_name='Статус кімнати'),
        ),
    ]
